### ISSUE TITLE
Feedback user 251: German translation is missing

### ISSUE THREAD

**Issue by sara-georgy** [stadtnavi/stadtnavi_app#182] opened 2021-06-14 15:11 UTC
The German translation for the following components is missing: 

- corner of path and parking aisle
- CAR
- BICYCLE

**Comment by Denis306** [comment] 2021-06-21 18:45
@sara-georgy Could you please check again and let me know if this  is issue is up to date?
I can't reproduce the "Corner of path and parking aisle" issue and the other ones should be fixed.

**Comment by sara-georgy** [comment] 2021-06-22 11:13
@Denis306 the "corner of path and parking aisle" is not reproducible anymore. 
However, I found another component that should be translated. (See Screenshot)

![image](https://user-images.githubusercontent.com/84382750/122915061-a04fc880-d35b-11eb-9881-e61060d38d9f.png)

**Comment by GustavoTCh** [comment] 2021-06-28 13:43
Resolved in https://github.com/trufi-association/trufi-core/pull/545

![Simulator Screen Shot - iPhone 11 Pro Max - 2021-06-28 at 15 39 40](https://user-images.githubusercontent.com/42806689/123646191-481b3980-d827-11eb-99f0-d8ee791e4be3.png)

![Simulator Screen Shot - iPhone 11 Pro Max - 2021-06-28 at 15 34 20](https://user-images.githubusercontent.com/42806689/123646211-4baec080-d827-11eb-9541-52ed0f231097.png)

**Closed** 2024-08-12 19:28 UTC
Labels: bug
