### ISSUE TITLE
Investigate how to set up GraphQL

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#3] opened 2021-04-23 15:15 UTC
We need to make it possible to work with GraphQL of OTP with the DevServer.

**Comment by hbruch** [comment] 2021-04-23 15:27
@leonardehrenfried will provide you with a graphiql instance which helps writing queries. Besides this, [HSL tutorial](https://digitransit.fi/en/developers/apis/1-routing-api/0-graphql/) provides a good introduction.

**Comment by GustavoTCh** [comment] 2021-04-26 13:58
Hi everyone.

I Have the next points about "how to set up GraphQL":

- I checked the documentation [HSL tutorial](https://digitransit.fi/en/developers/apis/1-routing-api/0-graphql/).
- I practiced queries with DevServer (https://api.dev.stadtnavi.eu/routing/v1/router/index/graphql) on graphiql.
- I researched on flutter-graphql, There is the recommended package on the [graphql ](https://graphql.org/code/) for flutter, this package has 2 elements graphql and flutter_graphql, also the package support flutter 2 in her pre-released version  `graphql_flutter: ^5.0.0-nullsafety.2` and use hive for cached.
- I went through the code in digit-transit-UI (NEXT) to walk me through the queries.
- GraphQL in Trufi-Core onboarding tests:
   - Install dependency(there are some dependencies conflicts when integrating graphql)
      - The package UUID must be updated to “uuid: ^3.0.1”
      - It is required to previously disable the devDependency "flutter_driver"
   - Graphql in trufi-core integration test(all stops)
   
![WhatsApp Image 2021-04-26 at 9 54 43 AM](https://user-images.githubusercontent.com/42806689/116094352-763c9b80-a675-11eb-8207-36e2b0c88207.jpeg)

**Comment by md-weber** [comment] 2021-04-26 14:04
Hi Gustavo, that are interesting news thanks for sharing, could you try to downgrade the graphql package by one major version. The problem is that the Integration Tests of Flutter are currently not upgraded to use UUID 3+.

**Comment by GustavoTCh** [comment] 2021-04-26 14:13
Ok @md-weber, I will check this.

**Comment by GustavoTCh** [comment] 2021-04-26 14:30
I tried with others downgrade, with `graphql_flutter: 4.0.1`the error is 

> trufi_core depends on 4.0.1 which depends on path_provider ^1.6.10, path_provider ^1.6.10 is required.

In other downgrade is more conflicts.

**Comment by md-weber** [comment] 2021-04-26 14:44
Ok do you have a branch I would love to take a look into that :)

**Comment by md-weber** [comment] 2021-05-09 06:03
I guess we are now able to work with GraphQL in Trufi Core, therefore I would close this issue.

**Closed by md-weber** 2021-05-09 06:03 UTC
Labels: enhancement
