### ISSUE TITLE
Fare display: change decimal separator and button link

### ISSUE THREAD

**Issue by nghanem-poet-egypt** [stadtnavi/stadtnavi_app#236] opened 2021-06-21 09:31 UTC
Fare display in itenerary: 

1. In German language: the price needs to have a comma , as decimal separator not a dot .
In English language: it should stay a dot

2. The button "Tickets kaufen" doesn't link to anything, it should have a link in the background or get removed --> In the ticket https://github.com/stadtnavi/digitransit-ui/issues/352 it is written to "Only display the "Book" button when the backend sends the URL."

![grafik](https://user-images.githubusercontent.com/84389152/122739567-67442500-d283-11eb-97dc-d1dfe6ce5299.png)

_Originally posted by @nghanem-poet-egypt in https://github.com/stadtnavi/stadtnavi_app/issues/121#issuecomment-864881107_

**Comment by GustavoTCh** [comment] 2021-06-23 21:08
Resolved in https://github.com/trufi-association/trufi-core/pull/538

![WhatsApp Image 2021-06-23 at 11 05 28 PM](https://user-images.githubusercontent.com/42806689/123168042-bb175f80-d477-11eb-9f8b-55e3c9535970.jpeg)

**Comment by GustavoTCh** [comment] 2021-06-24 00:24
@nghanem-poet-egypt  If for point 2 you used an Android> 29, the problem is not the backend, it is an App problem, which was resolved by @SamuelRioTz in this PR https://github.com/stadtnavi/stadtnavi_app/pull/253#pullrequestreview-691240716

**Comment by nghanem-poet-egypt** [comment] 2021-06-27 10:50
@GustavoTCh Currently I cannot validate this, because the ticket prices are not shown at all. I guess this is already reported somewhere else so I'll leave the issue open until the problem with displaying the ticket prices is solved. 
@Denis306 could you please write in which ticket this is reported?

**Closed** 2024-08-12 19:28 UTC
Labels: improvement
