### ISSUE TITLE
Feedback from Ansgar: closed parking places should not be used in the route suggestions 

### ISSUE THREAD

**Issue by sara-georgy** [stadtnavi/stadtnavi_app#204] opened 2021-06-16 08:18 UTC
Feedback ID: 29

The system should exclude the closed parking places from the route suggestions 

![image](https://user-images.githubusercontent.com/84382750/122184028-1c459e80-ce8c-11eb-92d8-dcd9dcc680ed.png)

**Comment by leonardehrenfried** [comment] 2021-06-16 09:15
To the frontend devs: This will be fixed by setting the parameter `useVehicleParkingAvailabilityInformation=true` in the Park and Ride GraphQL request. 
This should be set to true when the search starts within 15 minutes of now.

@sara-georgy This could still lead to confusion when the search is for tomorrow because the icon is always shown the current state (not the state of when the search starts). Can you clarify with Ansgar if this is ok? The alternative would be to use the state of the parking information _right now_ even when you search for tomorrow. This would be visually consistent but could be wrong as we don't know if the parking lot will be full tomorrow.

**Comment by leonardehrenfried** [comment] 2021-06-16 09:17
@Denis306 Can you ask the app team to also implement this parameter?

**Comment by Denis306** [comment] 2021-06-16 09:35
@leonardehrenfried Does this also have to do with this issue https://github.com/stadtnavi/digitransit-ui/issues/362 ? But yes, I will tell the app team.

**Comment by leonardehrenfried** [comment] 2021-06-16 09:38
It's very related but not quite. Perhaps I explain it after today's daily?

**Comment by sara-georgy** [comment] 2021-06-16 11:06
**Feedback from Ansgar:** Is is ok, if the icon shows the current state.

**Comment by Denis306** [comment] 2021-06-22 07:06
@GustavoTCh Is this not implemented already?

**Comment by GustavoTCh** [comment] 2021-06-22 09:25
@Denis306, this is implemented.

when you make the date within 15 min( ignore parking lots that don't have spaces)
![WhatsApp Image 2021-06-22 at 11 15 15 AM (1)](https://user-images.githubusercontent.com/42806689/122898602-4e06ab80-d34b-11eb-8786-fa1c0888eba6.jpeg)

when the date is outside 15 minutes
![WhatsApp Image 2021-06-22 at 11 15 15 AM](https://user-images.githubusercontent.com/42806689/122898606-4fd06f00-d34b-11eb-86ba-a58ba14b3f57.jpeg)

About the parking icon, It is another task, @SamuelRioTz  is more informed about the icon

**Comment by Denis306** [comment] 2021-06-22 09:39
@GustavoTCh Okay. I am moving this to "on internal" then.

**Comment by ahmed-nawar** [comment] 2021-06-22 12:38
> @Denis306, this is implemented.
> 
> when you make the date within 15 min( ignore parking lots that don't have spaces)
> ![WhatsApp Image 2021-06-22 at 11 15 15 AM (1)](https://user-images.githubusercontent.com/42806689/122898602-4e06ab80-d34b-11eb-8786-fa1c0888eba6.jpeg)
> 
> when the date is outside 15 minutes
> ![WhatsApp Image 2021-06-22 at 11 15 15 AM](https://user-images.githubusercontent.com/42806689/122898606-4fd06f00-d34b-11eb-86ba-a58ba14b3f57.jpeg)
> 
> About the parking icon, It is another task, @SamuelRioTz is more informed about the icon

@GustavoTCh How can I reproduce this same scenario?

**Comment by GustavoTCh** [comment] 2021-06-22 14:20
@ahmed-nawar it is a bit difficult, because The parking lots have different states over time (empty, semi-full, full).

You can use origin: Nufringen, destiny:Herrenberg 

You need to configure the map settings and enable the car option to see the parking lots.
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-06-22 at 15 52 27](https://user-images.githubusercontent.com/42806689/122938740-4eb33800-d373-11eb-9279-a0ee84c88994.png)

You must configure the settings, enable the option "Park & Ride"
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-06-22 at 16 04 34](https://user-images.githubusercontent.com/42806689/122939198-b9fd0a00-d373-11eb-8419-05ee0792d090.png)



First Case(the date within 15 min):
1. You need to request with the date option "Leaving now"
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-06-22 at 15 51 14](https://user-images.githubusercontent.com/42806689/122939507-f7619780-d373-11eb-9d55-51ff675e6576.png)

2. Enter the screen "Park & Ride"
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-06-22 at 16 09 23](https://user-images.githubusercontent.com/42806689/122939857-44456e00-d374-11eb-97e6-271c7061983e.png)

3. All options are for parking (empty , semi-full)
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-06-22 at 16 10 11](https://user-images.githubusercontent.com/42806689/122940322-a7cf9b80-d374-11eb-96d8-1ac24f27d96a.png)



Second Case(the date outside 15 min):
1. You need to select a date that is greater than the current one with a margin of 15 min, example (if it is 12:16 you need a date greater than or equal to 12:31)

2. Enter the screen "Park & Ride"
You need to select a date that is greater than the current one with a margin of 15 min, example (if it is 12:16 you need a date greater than or equal to 12:31)

![Simulator Screen Shot - iPhone 11 Pro Max - 2021-06-22 at 16 18 45](https://user-images.githubusercontent.com/42806689/122941423-ab175700-d375-11eb-96ec-51ee6b2c4271.png)

3. All options are for parking (empty , semi-full and full)
this image has first option a park-full
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-06-22 at 16 10 11](https://user-images.githubusercontent.com/42806689/122941219-7a372200-d375-11eb-8856-a7b207c501a4.png)

**Closed** 2024-08-12 19:27 UTC
Labels: bug, improvement
