### ISSUE TITLE
Grey screen after pressing reset button for address search

### ISSUE THREAD

**Issue by ahmed-nawar** [stadtnavi/stadtnavi_app#245] opened 2021-06-22 15:43 UTC
**Describe the bug**
When I press the `X` button next to the address search to reset the origin and destination addresses, the screen turns grey and it\s confusing until I search for another address to show the map.
**To Reproduce**
1. Set origin: Bahnhof Herrenberg (Or any other)
2. Set Destination: Stuttgart MainStation (Or any other)
3. After the route is loaded click on the reset `X` button
4. The screen turns grey

**Expected behavior**
An overview of Herrenberg's map would be shown
**Screenshots**
![MicrosoftTeams-image (21)](https://user-images.githubusercontent.com/84456072/122956362-3813dd80-d381-11eb-9b2f-bf1755254d83.png)

**Smartphone:**
- IOS v1.3.2
- Android 1.2.9

**Comment by Denis306** [comment] 2021-06-23 08:01
@ahmed-nawar I can't reproduce this. 

@SamuelRioTz As this is quite critical maybe you can check and try to reproduce.

**Comment by ahmed-nawar** [comment] 2021-06-23 09:40
@Denis306 Weird that today I cannot reproduce the issue. Yesterday, it always occurred. I think that it might have been a connection issue. I'll try to reproduce it.

**Comment by SamuelRioTz** [comment] 2021-06-24 00:21
@ahmed-nawar fixed on the last version.
it was happening when you have in focus some marker, then you search some route, and clean the search

**Closed** 2024-08-12 19:27 UTC
Labels: bug, improvement
